### ISSUE TITLE
Backtest example graphs in README.md need updating?

### ISSUE THREAD

**Issue by natemoser** [Heerozh/spectre#6]
I just downloaded pricing using 
```
from spectre.data import YahooDownloader
YahooDownloader.ingest(start_date="2001", save_to="./prices/yahoo", symbols=None, skip_exists=True)
```
and then ran the example code in 
https://github.com/Heerozh/spectre#back-testing
and got pretty different results, as seen in the screenshot below. 

Seems like this could either be updated/corrected pricing data from Yahoo, or changes in the example code? Looking at 
https://github.com/Heerozh/spectre/blame/master/README.md
it does look like there have a been a couple of changes to the code since the img link was added, and maybe the image just needs to be updated with results from the latest example code?

![image](https://user-images.githubusercontent.com/165148/84099802-07f4d900-a9d0-11ea-8253-b4e734c44971.png)

**Comment by Heerozh** [comment]
Yes, there are some changes in the code after adding this image.
Since this example purchased more than 300 stocks, so it is very sensitive to any changes. Generally, I will not update it unless some major bug fixes.

But I think the main reason is that yahoo's data is adjusted, that is, the data will change over time, the price data you download now is different from when I added this picture.

**Comment by natemoser** [comment]
Thanks, makes sense (and I hadn't considered that the set of SP500 tickers would change over time too!).
